Repository jenkinsci/htmlpublisher-plugin, pull requests merged in 2024-03, with the labels that each got.

#268 Fix test timeout when running in PCT
  src/test/java/htmlpublisher/HtmlPublisherIntegrationTest.java
Labels: internal, maintenance

#251 Add Plugin Development Team to CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#274 Remove unnecessary JARs from JPI
  pom.xml
Labels: internal
